### ISSUE TITLE
Error in generating depth map from epi

### ISSUE THREAD

**Issue by jie666-6** [hahnec/depthy#4]
I would like to generate depth map using my png file. But it always show error like this. Could you please help in this issue? Many thanks

(depth_map) C:\Workplace\02work>depthy -s D:\PNG\flood

depthy v0.4.0

Using epi method

Load light-field images

Traceback (most recent call last):
  File "c:\users\anaconda3\envs\depth_map\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\anaconda3\envs\depth_map\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\anaconda3\envs\depth_map\Scripts\depthy.exe\__main__.py", line 7, in <module>
  File "c:\users\anaconda3\envs\depth_map\lib\site-packages\depthy\bin\cli.py", line 138, in main
    lf_img_arr = load_lf_arr(filenames)
  File "c:\users\anaconda3\envs\depth_map\lib\site-packages\depthy\misc\io_functions.py", line 53, in load_lf_arr
    fnames = sorted(fnames, key=lambda x: int(re.sub("[^0-9]", "", os.path.basename(x).split(".")[0])))
  File "c:\users\anaconda3\envs\depth_map\lib\site-packages\depthy\misc\io_functions.py", line 53, in <lambda>
    fnames = sorted(fnames, key=lambda x: int(re.sub("[^0-9]", "", os.path.basename(x).split(".")[0])))
ValueError: invalid literal for int() with base 10: ''

**Comment by lonngxiang** [comment]
same error
